//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Kid Omar Costelo\Documents\School\3rd year 2nd sem\CODE-Interpreter\CODE-Interpreter\CODE-Interpreter\Content\Code.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CodeParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICodeListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CodeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CodeParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CodeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CodeParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CodeParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CodeParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CodeParser.initialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialization([NotNull] CodeParser.InitializationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CodeParser.initialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialization([NotNull] CodeParser.InitializationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CodeParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] CodeParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CodeParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] CodeParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CodeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CodeParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CodeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CodeParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CodeParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] CodeParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CodeParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] CodeParser.ConstantContext context);
}
